DATASET:
  NAME:                 SeamlessInteractionTalk
  LOADER:               sitalk_data.SeamlessInteractionTalkData
  CLIP_LENGTH:          100
  PREV_LENGTH:          100
  STYLE_LENGTH:         100
  MOTION_FPS:           25
  AUDIO_SAMPLE_RATE:    16000
  DATA_PATH:            /root/cpfs/datasets/UniLSTalkDataset/SeamlessInteractionTalk/data_lmdb
  META_PATH:            /root/cpfs/datasets/UniLSTalkDataset/SeamlessInteractionTalk/seamless_interaction_pairs.json