PIPELINE: 'vae_trainer.VAETrainer'
WANDB_ENTITY: 'xchu_ut'
WANDB_PROJECT: 'UniLS'
DUMP_DIR: './outputs'


DATASET:
  NAME: 'TalkMotionOnly'
  LOADER: 'motion_data.TalkMotionOnlyData'
  CLIP_LENGTH: 100
  PREV_LENGTH: 100
  STYLE_LENGTH: 100
  MOTION_FPS: 25
  AUDIO_SAMPLE_RATE: 16000
  DATA_PATH: '/home/mil/x-chu/workspace/Data_umiushi/UniLSTalkDataset/TalkMotionOnly/data_lmdb'
  META_PATH: '/home/mil/x-chu/workspace/Data_umiushi/UniLSTalkDataset/TalkMotionOnly/talk_motion.json'


MODEL:
  NAME: 'UniLSCodec'
  LOADER: 'unils_codec.UniLSCodec'
  MOTION_DIM: 108 # 100 + 3 + 1 + 2 + 2
  V_CODE_DIM: 32
  V_PATCH_NUMS: [1, 10, 20, 50, 100]
  T_DEPTH: 8
  T_NUM_HEADS: 8
  T_HIDDEN_DIM: 512
  STATS_PATH: '/home/mil/x-chu/workspace/Data_umiushi/UniLSTalkDataset/TalkMotionOnly/talk_motion_stats.json'


TRAINER:
  # TRAIN LOOP
  BATCH_SIZE: 64
  TRAIN_ITER: 200000
  CHECK_INTERVAL: 50000

  # OPTIMIZER
  NAME: 'Adam'
  WARMUP_ITER: 1000
  LR_DECAY_RATE: 0.1
  LR_DECAY_ITER: 200000
  LEARNING_RATE: 1.0e-4

  # EMA
  USING_EMA: True
  EMA_DECAY: 0.9999
  EMA_UPDATE_FREQ: 1


LOSS_KWARGS:
  # GEO_LOSS: True
  VQ_WEIGHT: 1.0
  EXP_WEIGHT: 1.0
  POSE_WEIGHT: 8.0
  HEAD_VEL_WEIGHT: 5.0
  HEAD_SMOOTH_WEIGHT: 0.5
  MESH_WEIGHT: 2.0
  LIPS_WEIGHT: 0.1
  MESH_VEL_WEIGHT: 10000000.0
  MESH_SMOOTH_WEIGHT: 100000.0
